import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(
    os.path.dirname(BASE_DIR),
    "data"
)
OUTPUT_DIR = os.path.join(BASE_DIR, "outputs")

RANDOM_SEED = 42

CUTOFF_DATE = "2024-06-06"
CUTOFF_2005 = "2005-01-01"

CLASS_LIMITS = {
    "Flyweight": 125,
    "Bantamweight": 135,
    "Featherweight": 145,
    "Lightweight": 155,
    "Welterweight": 170,
    "Middleweight": 185,
    "Light Heavyweight": 205,
    "Heavyweight": 265,
    "Women's Strawweight": 115,
    "Women's Flyweight": 125,
    "Women's Bantamweight": 135,
    "Women's Featherweight": 145,
}

FEATURE_GROUPS = {
    "Striking Volume": [
        "fighter_r_sig_landed_per_fight", "fighter_b_sig_landed_per_fight",
        "fighter_r_sig_absorbed_per_fight", "fighter_b_sig_absorbed_per_fight",
        "fighter_r_sig_diff_per_fight", "fighter_b_sig_diff_per_fight",
    ],
    "Striking Accuracy": ["fighter_r_sig_acc", "fighter_b_sig_acc"],
    "Striking Defense": ["fighter_r_striking_defense", "fighter_b_striking_defense"],
    "Knockdowns": ["fighter_r_kd_per_fight", "fighter_b_kd_per_fight"],
    "Takedowns": [
        "fighter_r_td_landed_per_fight", "fighter_b_td_landed_per_fight",
        "fighter_r_td_diff_per_fight", "fighter_b_td_diff_per_fight",
    ],
    "TD Accuracy": ["fighter_r_td_acc", "fighter_b_td_acc"],
    "TD Defense": ["fighter_r_td_defense", "fighter_b_td_defense"],
    "Control": ["fighter_r_ctrl_sec_per_fight", "fighter_b_ctrl_sec_per_fight"],
    "Submissions": ["fighter_r_sub_att_per_fight", "fighter_b_sub_att_per_fight"],
    "Composite Striking": [
        "fighter_r_striking_score", "fighter_b_striking_score",
        "striking_score_diff",
    ],
    "Composite Grappling": [
        "fighter_r_grappling_score", "fighter_b_grappling_score",
        "grappling_score_diff",
    ],
    "Adjusted Striking": ["adjusted_striking_r", "adjusted_striking_b"],
    "Adjusted Grappling": ["adjusted_grappling_r", "adjusted_grappling_b"],
    "ELO": [
        "fighter_r_elo", "fighter_b_elo", "elo_diff",
        "fighter_r_elo_finish", "fighter_b_elo_finish", "elo_finish_diff",
    ],
    "Experience": [
        "fighter_r_num_fights", "fighter_b_num_fights", "num_fights_diff",
        "fighter_r_champ_round_experience", "fighter_b_champ_round_experience",
        "champ_exp_diff", "fighter_r_is_debut", "fighter_b_is_debut",
    ],
    "Win Rates": [
        "fighter_r_win_rate", "fighter_b_win_rate",
        "fighter_r_finish_rate", "fighter_b_finish_rate",
        "fighter_r_ko_rate", "fighter_b_ko_rate",
        "fighter_r_sub_rate", "fighter_b_sub_rate",
    ],
    "Opponent Quality": [
        "fighter_r_avg_opp_elo", "fighter_b_avg_opp_elo",
        "fighter_r_avg_opp_win_rate", "fighter_b_avg_opp_win_rate",
        "fighter_r_avg_opp_finish_rate", "fighter_b_avg_opp_finish_rate",
        "fighter_r_opponent_elo", "fighter_b_opponent_elo",
    ],
    "Streaks": [
        "fighter_r_win_streak", "fighter_b_win_streak",
        "fighter_r_loss_streak", "fighter_b_loss_streak",
        "fighter_r_streak_diff", "fighter_b_streak_diff",
    ],
    "Recent Form": [
        "fighter_r_recent_sig_landed_3", "fighter_b_recent_sig_landed_3",
        "fighter_r_recent_ctrl_sec_3", "fighter_b_recent_ctrl_sec_3",
        "fighter_r_recent_finish_rate_3", "fighter_b_recent_finish_rate_3",
    ],
    "Recency": [
        "fighter_r_days_since_last_fight", "fighter_b_days_since_last_fight",
        "fighter_r_days_since_last_loss", "fighter_b_days_since_last_loss",
    ],
    "Weight Cut": [
        "fighter_r_weight_cut_pct", "fighter_b_weight_cut_pct",
        "fighter_r_weight_class_changed", "fighter_b_weight_class_changed",
    ],
}

ADVANTAGE_FEATURE_COLS = [
    "elo_diff",
    "striking_score_diff",
    "grappling_score_diff",
    "num_fights_diff",
    "champ_exp_diff",
    "reach_diff",
    "height_diff",
    "age_diff",
    "fighter_r_southpaw",
    "weight_diff",
]

FEATURE_LABELS = {
    "elo_diff": "ELO Rating Advantage",
    "striking_score_diff": "Striking Advantage",
    "grappling_score_diff": "Grappling Advantage",
    "num_fights_diff": "Experience Advantage",
    "champ_exp_diff": "Champ. Experience",
    "reach_diff": "Reach Advantage",
    "height_diff": "Height Advantage",
    "age_diff": "Age Advantage",
    "weight_diff": "Weight Advantage",
    "fighter_r_southpaw": "Red Southpaw",
    "fighter_b_southpaw": "Blue Southpaw",
    "fighter_r_elo": "Red ELO",
    "fighter_b_elo": "Blue ELO",
    "fighter_r_elo_finish": "Red Finish ELO",
    "fighter_b_elo_finish": "Blue Finish ELO",
    "elo_finish_diff": "Finish ELO Advantage",
    "fighter_r_striking_defense": "Red Strike Defense",
    "fighter_b_striking_defense": "Blue Strike Defense",
    "fighter_r_sig_landed_per_fight": "Red Strikes Landed/Fight",
    "fighter_b_sig_landed_per_fight": "Blue Strikes Landed/Fight",
    "fighter_r_sig_absorbed_per_fight": "Red Strikes Absorbed/Fight",
    "fighter_b_sig_absorbed_per_fight": "Blue Strikes Absorbed/Fight",
    "fighter_r_sig_diff_per_fight": "Red Strike Diff/Fight",
    "fighter_b_sig_diff_per_fight": "Blue Strike Diff/Fight",
    "fighter_r_sig_acc": "Red Strike Accuracy",
    "fighter_b_sig_acc": "Blue Strike Accuracy",
    "fighter_r_td_defense": "Red TD Defense",
    "fighter_b_td_defense": "Blue TD Defense",
    "fighter_r_td_landed_per_fight": "Red TDs/Fight",
    "fighter_b_td_landed_per_fight": "Blue TDs/Fight",
    "fighter_r_td_diff_per_fight": "Red TD Diff/Fight",
    "fighter_b_td_diff_per_fight": "Blue TD Diff/Fight",
    "fighter_r_td_acc": "Red TD Accuracy",
    "fighter_b_td_acc": "Blue TD Accuracy",
    "fighter_r_ctrl_sec_per_fight": "Red Control/Fight",
    "fighter_b_ctrl_sec_per_fight": "Blue Control/Fight",
    "fighter_r_kd_per_fight": "Red KDs/Fight",
    "fighter_b_kd_per_fight": "Blue KDs/Fight",
    "fighter_r_sub_att_per_fight": "Red Sub Att./Fight",
    "fighter_b_sub_att_per_fight": "Blue Sub Att./Fight",
    "fighter_r_striking_score": "Red Striking Score",
    "fighter_b_striking_score": "Blue Striking Score",
    "fighter_r_grappling_score": "Red Grappling Score",
    "fighter_b_grappling_score": "Blue Grappling Score",
    "adjusted_striking_r": "Red Adj. Striking",
    "adjusted_striking_b": "Blue Adj. Striking",
    "adjusted_grappling_r": "Red Adj. Grappling",
    "adjusted_grappling_b": "Blue Adj. Grappling",
    "fighter_r_num_fights": "Red Experience",
    "fighter_b_num_fights": "Blue Experience",
    "fighter_r_win_rate": "Red Win Rate",
    "fighter_b_win_rate": "Blue Win Rate",
    "fighter_r_finish_rate": "Red Finish Rate",
    "fighter_b_finish_rate": "Blue Finish Rate",
    "fighter_r_ko_rate": "Red KO Rate",
    "fighter_b_ko_rate": "Blue KO Rate",
    "fighter_r_sub_rate": "Red Sub Rate",
    "fighter_b_sub_rate": "Blue Sub Rate",
    "fighter_r_avg_opp_elo": "Red Avg Opp. ELO",
    "fighter_b_avg_opp_elo": "Blue Avg Opp. ELO",
    "fighter_r_avg_opp_win_rate": "Red Avg Opp. Win Rate",
    "fighter_b_avg_opp_win_rate": "Blue Avg Opp. Win Rate",
    "fighter_r_avg_opp_finish_rate": "Red Avg Opp. Finish Rate",
    "fighter_b_avg_opp_finish_rate": "Blue Avg Opp. Finish Rate",
    "fighter_r_opponent_elo": "Red Opp. ELO",
    "fighter_b_opponent_elo": "Blue Opp. ELO",
    "fighter_r_win_streak": "Red Win Streak",
    "fighter_b_win_streak": "Blue Win Streak",
    "fighter_r_loss_streak": "Red Loss Streak",
    "fighter_b_loss_streak": "Blue Loss Streak",
    "fighter_r_streak_diff": "Red Streak Diff",
    "fighter_b_streak_diff": "Blue Streak Diff",
    "fighter_r_recent_sig_landed_3": "Red Recent Strikes (3)",
    "fighter_b_recent_sig_landed_3": "Blue Recent Strikes (3)",
    "fighter_r_recent_ctrl_sec_3": "Red Recent Control (3)",
    "fighter_b_recent_ctrl_sec_3": "Blue Recent Control (3)",
    "fighter_r_recent_finish_rate_3": "Red Recent Finish (3)",
    "fighter_b_recent_finish_rate_3": "Blue Recent Finish (3)",
    "fighter_r_days_since_last_fight": "Red Days Since Fight",
    "fighter_b_days_since_last_fight": "Blue Days Since Fight",
    "fighter_r_days_since_last_loss": "Red Days Since Loss",
    "fighter_b_days_since_last_loss": "Blue Days Since Loss",
    "fighter_r_weight_cut_pct": "Red Weight Cut %",
    "fighter_b_weight_cut_pct": "Blue Weight Cut %",
    "fighter_r_weight_class_changed": "Red Wt. Class Changed",
    "fighter_b_weight_class_changed": "Blue Wt. Class Changed",
    "fighter_r_is_debut": "Red Debut",
    "fighter_b_is_debut": "Blue Debut",
    "same_stance": "Same Stance",
    "adjusted_striking_r": "Red Adj. Striking",
    "adjusted_striking_b": "Blue Adj. Striking",
    "adjusted_grappling_r": "Red Adj. Grappling",
    "adjusted_grappling_b": "Blue Adj. Grappling",
}

XGB_PARAMS = {
    "n_estimators": 500,
    "max_depth": 6,
    "learning_rate": 0.03,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "eval_metric": "logloss",
    "early_stopping_rounds": 20,
    "random_state": RANDOM_SEED,
}

RF_PARAMS = {
    "n_estimators": 500,
    "max_depth": 10,
    "min_samples_leaf": 5,
    "random_state": RANDOM_SEED,
    "n_jobs": -1,
}

LR_PARAMS = {
    "C": 1.0,
    "max_iter": 1000,
    "random_state": RANDOM_SEED,
    "solver": "lbfgs",
}
